# services:
#   django:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: django_app
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     environment:
#       - REDIS_HOST=redis
#       - REDIS_PORT=6379
#     depends_on:
#       - redis

#   redis:
#     image: redis:latest
#     container_name: redis
#     ports:
#       - "6379:6379"

version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - celery

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
    container_name: celery_worker
    command: celery -A CONFIG worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
